AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  mrswordsmith-technical-test-api

  Sample SAM Template for mrswordsmith-technical-test-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Architectures:
      - arm64
    Runtime: nodejs18.x

Resources:
  AccountCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: account-api/
      Handler: accountApiHandler.create
      Events:
        AccountCreate:
          Type: HttpApi
          Properties:
            Path: /account
            Method: post
      Environment:
        Variables:
          ACCOUNTS_TABLE_NAME: !Ref AccountsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - accountApiHandler.ts

  AccountUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: account-api/
      Handler: accountApiHandler.update
      Events:
        AccountUpdate:
          Type: HttpApi
          Properties:
            Path: /account/{id}
            Method: put
      Environment:
        Variables:
          ACCOUNTS_TABLE_NAME: !Ref AccountsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - accountApiHandler.ts

  AccountGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: account-api/
      Handler: accountApiHandler.get
      Events:
        AccountGet:
          Type: HttpApi
          Properties:
            Path: /account/{id}
            Method: get
      Environment:
        Variables:
          ACCOUNTS_TABLE_NAME: !Ref AccountsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - accountApiHandler.ts

  AccountDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: account-api/
      Handler: accountApiHandler.remove
      Events:
        AccountDelete:
          Type: HttpApi
          Properties:
            Path: /account/{id}
            Method: delete
      Environment:
        Variables:
          ACCOUNTS_TABLE_NAME: !Ref AccountsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - accountApiHandler.ts

  AccountListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: account-api/
      Handler: accountApiHandler.getAll
      Events:
        AccountGet:
          Type: HttpApi
          Properties:
            Path: /accounts
            Method: get
      Environment:
        Variables:
          ACCOUNTS_TABLE_NAME: !Ref AccountsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - accountApiHandler.ts

  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Accounts
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
